language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
addons:
  apt:
    packages:
    - git
install:
    - pip install tox tox-travis codecov
script:
    - tox
after_success:
    - codecov
